# Rime default settings
# encoding: utf-8

config_version: '0.40'

schema_list:
  - schema: tiger_code     # 主方案1：虎单
  - schema: tiger_code_exp # 主方案2：赫兹虎延迟顶
  - schema: tiger_codes    # 次方案：官方虎词
  - schema: tiger_oni      # 次方案：九重鬼虎
  - schema: tiger_phrase   # 整活方案1：赫兹虎单整句
  - schema: tiger_phrases  # 整活方案2：官方虎词整句
  - schema: easy_en        # 方案集成

switcher:
  caption: "〔方案選單〕"
  hotkeys:
    - "Control+grave"
    - "Control+F8"
  save_options:
    - full_shape
    - ascii_punct
    - traditionalization
    - emoji
    - extended_char
    - mars
    - prediction
    - tiger_spelling.off
    - tiger_spelling.lv1
    - tiger_spelling.lv2
    - tiger_spelling.lv3
    - tiger_spelling.lv4
  fold_options: true
  abbreviate_options: true
  option_list_separator: '／'

menu:
  alternative_select_labels: [ ⑴, ⑵, ⑶, ⑷, ⑸, ⑹, ⑺, ⑻, ⑼, ⑽ ]
  page_size: 9

punctuator:
  __include: tiger:/punctuator

key_binder:
  import_preset: default
  bindings:
    __patch:
      - tiger:/keys/page_up_down
      - tiger:/keys/selector
      - tiger:/keys/options_toggle

recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: clear
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
    Shift_L: commit_code
    Shift_R: commit_text
