from datetime import datetime

# 生成头部信息
header = f'''# Rime dictionary
# encoding: utf-8
# Generated by Hertz Hwang <https://github.com/hertz-hwang>

---
name: moss.base
version: "{datetime.now().strftime('%Y.%m.%d')}"
sort: by_weight
use_preset_vocabulary: false
columns:
  - text
  - code
  - weight
...
'''

# 处理文件
entries = []  # 存储所有条目

# 读取所有条目
with open('data/moss_tiger.txt', 'r', encoding='utf-8') as f_in:
    for line in f_in:
        # 跳过空行
        line = line.strip()
        if not line or line.startswith('...'):
            continue
            
        # 跳过行号
        if '|' in line:
            line = line.split('|')[1].strip()
            
        if line:
            # 分割字、编码和权重
            parts = line.split('\t')
            if len(parts) == 3:
                char, code, weight = parts
                # 处理编码格式，将分号替换为]，并在需要时补零
                code = code.replace(';', ']')
                # 检查是否需要在]后补零
                if ']' in code:
                    prefix, suffix = code.split(']')
                    if len(suffix) == 1:  # 如果]后只有一个字符
                        code = f"{prefix}]{suffix}0"
                entries.append((char, code, int(weight)))

# 按权重降序排序
entries.sort(key=lambda x: x[2], reverse=True)

# 写入排序后的结果
with open('../dicts/moss.base.dict.yaml', 'w', encoding='utf-8') as f_out:
    # 写入头部
    f_out.write(header + '\n')
    
    # 写入排序后的条目
    for char, code, weight in entries:
        f_out.write(f'{char}\t{code}\t{weight}\n')
