#!/usr/bin/env python3
from datetime import datetime

def convert_diff_to_dict():
    header = f'''# Rime dictionary
# encoding: utf-8
# Generated by Hertz Hwang <https://github.com/hertz-hwang>

---
name: moss.sogou_pop
version: "{datetime.now().strftime('%Y.%m.%d')}"
sort: by_weight
use_preset_vocabulary: false
columns:
  - text
  - code
  - weight
...

'''
    
    # 读取diff_sg.txt
    with open('diff_sg.txt', 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 写入新文件
    with open('diff_sg.dict.yaml', 'w', encoding='utf-8') as f:
        f.write(header + content)

if __name__ == "__main__":
    convert_diff_to_dict() 